### ISSUE TITLE
Highlight TextArea cursor bug

### ISSUE THREAD

**Issue by fgnm** [kotcrab/vis-ui#338] opened 2020-08-29 20:24 UTC
I've found another bug in `HighlightTextArea`. Highlighted text seams cause a visual bug in the cursor that is not able to determine the correct position of a single char.
In this GIF you can see the bug in Test Application when many words are highlighted on the same line:

![highlight_bug](https://user-images.githubusercontent.com/5543339/91644886-a6795f00-ea40-11ea-8bf6-e2367d615ed6.gif)

Not sure to what is related, because in the code I can see just `font.setColor` and `font.draw` nothing that should change char width. Here it's clear that the highlighted `a` is different:
![immagine](https://user-images.githubusercontent.com/5543339/91645308-5bf9e180-ea44-11ea-92e6-72b8068d9768.png) ![immagine](https://user-images.githubusercontent.com/5543339/91645314-69af6700-ea44-11ea-9448-990f87778faa.png)

I've found also a workaround (for to my use case and my font type) using `setFixedWidthGlyphs` in `BitmapFont`:
```Java
BitmapFont defaultMono = monoGenerator.generateFont(parameter);
defaultMono.setFixedWidthGlyphs(parameter.characters);
```

**Comment by kotcrab** [comment] 2020-08-30 08:33
Duplicate of #306, this shouldn't happen with monospaced font. Though I don't why why you would still need to call `setFixedWidthGlyphs` even when using monospaced font.

> Looks like this is an issue with kerning. X offset of highlight is calculated only on the highlighted text itself while cursor is using glyph positions calculated on the entire text. Unfortunately I'm not seeing an easy fix for this.

**Closed by kotcrab** 2020-08-30 08:33 UTC
Labels: bug, ui
